# The name of the workflow as it will appear in the GitHub Actions tab.
name: Tests

# The events that trigger this workflow.
on:
  - push # Triggers on every push to the repository.
  - pull_request # Triggers on every pull request created or updated.

# The list of jobs to be run in this workflow.
jobs:
  # The name of a specific job.
  test:
    # A job's run environment. 'matrix.os' refers to a variable from the strategy matrix.
    runs-on: ${{ matrix.os }}

    # A strategy is a way to create a matrix of different job configurations.
    strategy:
      # A matrix is a set of key-value pairs that defines different permutations of a job.
      matrix:
        # The 'os' key specifies a list of operating systems to run the job on.
        os: [ubuntu-latest, windows-latest]
        # The 'python-version' key specifies a list of Python versions to use.
        python-version: ["3.8", "3.9"]

    # The steps within a job. These are a sequence of tasks to be executed.
    steps:
      - # Uses a pre-built action to check out the repository's code.
        uses: actions/checkout@v2

      - # A named step for setting up Python.
        name: Set up Python ${{ matrix.python-version }}
        # Uses a pre-built action to set up a specific Python version.
        uses: actions/setup-python@v2
        with:
          # 'with' specifies inputs for the action. 'python-version' is a variable from the matrix.
          python-version: ${{ matrix.python-version }}

      - # A named step to install the necessary dependencies.
        name: Install dependencies
        # The 'run' keyword executes a command-line script.
        run: |
          # Installs and upgrades pip, the Python package installer.
          python -m pip install --upgrade pip
          # Installs 'tox' and 'tox-gh-actions' for running tests.
          pip install tox tox-gh-actions

      - # A named step to execute the test suite.
        name: Test with tox
        # 'tox' is a testing automation tool that runs tests in isolated environments.
        run: tox
